@startuml ERDiagramm

class Пользователь
{
    # строка Логин(почта)
    строка Имя
    строка Фамилия
    строка Отчество
    строка Хеш пароля
    + целое число Номер группы
}

class Роль
{
    # счётчик Номер
    строка Наименование роли
}

class "Пользователь-Роль"
{
    + строка Логин
    + целое число Номер Роли
}

class "Лабораторная Работа"
{
    # счётчик Номер лабораторной работы
    строка Название лабораторной работы
    строка Описание
    данные json Ограниченияп программы(Память, процессорное время и пр.)
    + строка Шифр дисциплины
    + целое число Номер пользователя
}

class Вариант
{
    # счётчик Номер
    + целое число Номер задания
    целое число Номер варианта
    строка Описание варианта
    строка Ссылка до эталонного решения
    данные json Предопределённые тестовые данные
}

class "Решённый Вариант"
{
    # счётчик Номер
    + целое число Номер варианта
    + строка Номер пользователя
    строка Исходный код
    дата и время Время отправки
    логический Тестовые прогоны выполненны успешно
}

class "Тестовый Прогон"
{
    # счётчик Номер тестового прогона
    + целое число Номер решённого варианта
    массив строк Входные данные
    массив строк Выходные данные
    данные json Результаты прогона
}

class Группа
{
    # счётчик Номер группы
    строка Символьное наименование
    целое число Год начала обучания
    + строка Код специальности
}

class Дисциплина
{
    # строка Шифр
    строка Наименование
}

class "Данные антиплагиата"
{
    # счётчик Код
    + целое число Номер решённого варианта
    + целое число Номер решённого варианта
    массив вещественных чисел Данные алгоритма
}

class "Статистика антиплагиата"
{
    # счётчик Код
    + целое число Номер пользователя
    дата и время Дата проверки
    строка Настройки проверки
}

class "Шаблон лабораторной работы"
{
    # счётчик Код шаблона
    строка Шаблон задания
}

class Специальность
{
    # строка Код специальности
    строка Наименование
}

"Пользователь-Роль" "много" }-- "1" Пользователь
"Пользователь-Роль" "много "}-- "1" Роль

"Лабораторная Работа" "много" }-- "1" Дисциплина
"Данные антиплагиата" "много" }-- "1" "Решённый Вариант"
Вариант "много" }-- "1" "Лабораторная Работа"
"Решённый Вариант" "много" }-- "1" Вариант
"Решённый Вариант" "много" }-- "1" Пользователь
Пользователь "много" }-- "1" Группа
Группа "много" }-- "1" Специальность
"Статистика антиплагиата" "много" }-- "1" Пользователь
"Лабораторная Работа" "много" }-- "1" "Шаблон лабораторной работы"
"Лабораторная Работа" "много" }-- "1" Пользователь
"Тестовый Прогон" "много" }-- "1" "Решённый Вариант"

@enduml