@startuml ERDiagramm

class Пользователь
{
    # строка Логин-Email
    + целое число Номер группы
    строка Имя
    строка Фамилия
    строка Отчество
    строка Хеш пароля
}

class Роль
{
    # счётчик Код роли
    строка Наименование роли
}

class "Пользователь-Роль"
{
    # счётчик Код Пользователь-Роль
    + строка Логин
    + целое число Номер Роли
}

class "Лабораторная Работа"
{
    # счётчик Код лабораторной работы
    строка Название лабораторной работы
    строка Описание
    данные json Ограниченияп программы(Память, процессорное время и пр.)
    + строка Шифр дисциплины
    + целое число Номер пользователя
}

class Вариант
{
    # счётчик Код варинта
    + целое число Код лабораторной работы
    целое число Номер варианта
    строка Описание варианта
    строка Ссылка до эталонного решения
    данные json Предопределённые тестовые данные
}

class "Решённый Вариант"
{
    # счётчик Код решенного варианта
    + целое число Номер назначенного варианта
    целое число Количество ошибок компиляции
    строка Исходный код
    дата и время Время отправки
    логический Тестовые прогоны выполненны успешно
}

class "Тестовый Прогон"
{
    # счётчик Код тестового прогона
    + целое число Номер решённого варианта
    массив строк Входные данные
    массив строк Выходные данные
    данные json Результаты прогона
}

class Группа
{
    # счётчик Код группы
    строка Символьное наименование
    целое число Год начала обучания
    + строка Код специальности
}

class Дисциплина
{
    # строка Шифр
    строка Наименование
}

class "Данные антиплагиата"
{
    # счётчик Код данных антиплагиата
    + целое число Номер решённого варианта
    + целое число Номер решённого варианта
    массив вещественных чисел Данные алгоритма
}

class "Статистика антиплагиата"
{
    # счётчик Код статистики антиплагиата
    + целое число Номер пользователя
    дата и время Дата проверки
    строка Настройки проверки
}

class "Шаблон лабораторной работы"
{
    # счётчик Код шаблона
    строка Шаблон задания
}

class Специальность
{
    # строка Код специальности
    строка Наименование
}

class Тема
{
    # счётчик Код темы
    строка Наименование темы
}

class "Назначенный вариант"
{
    # счётчик Код назначенного варианта
    + целое число Номер пользователя
    + целое число Номер варианта
}


class "Учебный план"
{
    # счётчик Код учебного плана
    + целое число Номер группы
    + целое число Номер дисциплины
    + целое число Пользователь |Преподователь|
}

"Пользователь-Роль" "много" }-- "1" Пользователь
"Пользователь-Роль" "много "}-- "1" Роль

"Лабораторная Работа" "много" }-- "1" Дисциплина
"Данные антиплагиата" "много" }-- "1" "Решённый Вариант"
Вариант "много" }-- "1" "Лабораторная Работа"
"Назначенный вариант" "много" }-- "1" Вариант
"Назначенный вариант" "много" }-- "1" Пользователь
"Решённый Вариант" "много" }-- "1" "Назначенный вариант"
Пользователь "много" }-- "1" Группа
Группа "много" }-- "1" Специальность
"Лабораторная Работа" "много" }-- "1" Тема
"Шаблон лабораторной работы" "много" }-- "1" Тема
"Статистика антиплагиата" "много" }-- "1" Пользователь
"Лабораторная Работа" "много" }-- "1" "Шаблон лабораторной работы"
"Лабораторная Работа" "много" }-- "1" Пользователь
"Тестовый Прогон" "много" }-- "1" "Решённый Вариант"
"Учебный план" "много" }-- "1" Группа
"Учебный план" "много" }-- "1" Дисциплина
"Учебный план" "много" }-- "1" Пользователь
@enduml